### ISSUE TITLE
Document "Unexpected token" error caused in node versions < 7

### ISSUE THREAD

**Issue by rajeevdesai** [froala/design-blocks#55]
While running the code for the first time after clone and `npm install`, I got the following error
```
/home/neo/open-source-dev/design-blocks/utils/index.js:23
async function makeScreenshotsByName(name, selector) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/neo/open-source-dev/design-blocks/gulpfile.js:8:13)
```
This was being caused as I have node 6.11.5, which does not support `async`.

I feel like this must be documented and alternatives such as transpiling the code using babel must be noted in the readme.

**Comment by stefanneculai** [comment]
@zouxuoz do you have any suggestions for this?

**Comment by stefanneculai** [comment]
I am going to close this for now as Node 6 is quite old now.
