### ISSUE TITLE
Gulp Error

### ISSUE THREAD

**Issue by isvictorious** [froala/design-blocks#68]
Got this error after following instructions:

design-blocks/utils/index.js:23
async function makeScreenshotsByName(name, selector) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/victorramirez/Desktop/Thinkful-2017/design-blocks/gulpfile.js:8:13)

**Comment by dianaprajescu** [comment]
@isvictorious try upgrading your Node version. Async functions are not supported by Node versions older than 7.6. `node -v` should show your current version.

Please let us know if this fixes your issue.

**Comment by isvictorious** [comment]
Wow. I'm an idiot. Got it running. Still get an error doing 'npm run gulp' but all good if I just 'gulp'

Can't wait to contribute. Thanks
